-- ==============================================================================
-- LabourLink Complete Database Schema & Migration for Supabase (PostgreSQL)
-- Project: https://rvjpikckmvossbvobzsx.supabase.co
-- ==============================================================================
-- Instructions:
-- 1. Open your Supabase Dashboard: https://supabase.com/dashboard/project/rvjpikckmvossbvobzsx/sql
-- 2. Click "New Query".
-- 3. Paste this entire script into the query editor and click "Run".
-- ==============================================================================

-- 1. Workers Table
CREATE TABLE IF NOT EXISTS workers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone_number TEXT UNIQUE NOT NULL,
  skill_type TEXT NOT NULL,
  location TEXT NOT NULL,
  available BOOLEAN DEFAULT TRUE,
  status TEXT DEFAULT 'AVAILABLE',
  current_active_job_id BIGINT DEFAULT NULL,
  current_location_zone TEXT DEFAULT NULL,
  registered_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migrations for existing workers table
ALTER TABLE workers ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'AVAILABLE';
ALTER TABLE workers ADD COLUMN IF NOT EXISTS current_active_job_id BIGINT DEFAULT NULL;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS current_location_zone TEXT DEFAULT NULL;

-- 2. Jobs Table
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_name TEXT NOT NULL,
  employer_phone TEXT NOT NULL,
  skill_needed TEXT NOT NULL,
  location TEXT NOT NULL,
  wage_offered TEXT NOT NULL,
  date_needed TEXT NOT NULL,
  status TEXT DEFAULT 'open',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Job Interests Table
CREATE TABLE IF NOT EXISTS job_interests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  worker_id BIGINT NOT NULL REFERENCES workers(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'interested',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_job_worker UNIQUE (job_id, worker_id)
);

-- 4. Worker CV Table (Structured Form Data)
CREATE TABLE IF NOT EXISTS worker_cv (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT UNIQUE NOT NULL REFERENCES workers(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  dob_or_age TEXT,
  phone_number TEXT,
  skills TEXT,
  years_of_experience INTEGER DEFAULT 0,
  previous_work TEXT,
  work_location TEXT,
  daily_wage_expectation TEXT,
  availability_type TEXT DEFAULT 'Full-time',
  languages TEXT,
  about_me TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Worker Ratings Table (1-5 stars with comments, prevent duplicate per job)
CREATE TABLE IF NOT EXISTS worker_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT NOT NULL REFERENCES workers(id) ON DELETE CASCADE,
  employer_phone TEXT,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  rating REAL NOT NULL CHECK (rating >= 1.0 AND rating <= 5.0),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_job_worker_rating UNIQUE (job_id, worker_id)
);

-- Indexes for optimal performance
CREATE INDEX IF NOT EXISTS idx_workers_skill_loc ON workers (skill_type, location, available);
CREATE INDEX IF NOT EXISTS idx_workers_phone ON workers (phone_number);
CREATE INDEX IF NOT EXISTS idx_jobs_skill_loc ON jobs (skill_needed, location, status);
CREATE INDEX IF NOT EXISTS idx_jobs_employer_phone ON jobs (employer_phone);
CREATE INDEX IF NOT EXISTS idx_job_interests_job ON job_interests (job_id);
CREATE INDEX IF NOT EXISTS idx_job_interests_worker ON job_interests (worker_id);
CREATE INDEX IF NOT EXISTS idx_worker_cv_worker ON worker_cv (worker_id);
CREATE INDEX IF NOT EXISTS idx_worker_ratings_worker ON worker_ratings (worker_id);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE worker_cv ENABLE ROW LEVEL SECURITY;
ALTER TABLE worker_ratings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if re-running
DROP POLICY IF EXISTS "Allow all for workers" ON workers;
DROP POLICY IF EXISTS "Allow all for jobs" ON jobs;
DROP POLICY IF EXISTS "Allow all for job_interests" ON job_interests;
DROP POLICY IF EXISTS "Allow all for worker_cv" ON worker_cv;
DROP POLICY IF EXISTS "Allow all for worker_ratings" ON worker_ratings;

-- Policies allowing full access via anon and authenticated roles
CREATE POLICY "Allow all for workers" ON workers
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for jobs" ON jobs
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for job_interests" ON job_interests
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for worker_cv" ON worker_cv
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for worker_ratings" ON worker_ratings
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Explicit table and sequence permissions for anon and authenticated API clients
GRANT ALL ON TABLE workers TO anon, authenticated;
GRANT ALL ON TABLE jobs TO anon, authenticated;
GRANT ALL ON TABLE job_interests TO anon, authenticated;
GRANT ALL ON TABLE worker_cv TO anon, authenticated;
GRANT ALL ON TABLE worker_ratings TO anon, authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
