-- ==============================================================================
-- LabourLink Database Schema for Supabase (PostgreSQL)
-- ==============================================================================
-- Instructions:
-- 1. Open your Supabase Dashboard (https://supabase.com/dashboard).
-- 2. Select your project.
-- 3. Click "SQL Editor" in the left sidebar.
-- 4. Paste this entire script into the query editor and click "Run".
-- ==============================================================================

-- 1. Workers Table
CREATE TABLE IF NOT EXISTS workers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone_number TEXT UNIQUE NOT NULL,
  skill_type TEXT NOT NULL,
  location TEXT NOT NULL,
  available BOOLEAN DEFAULT TRUE,
  registered_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Jobs Table
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_name TEXT NOT NULL,
  employer_phone TEXT NOT NULL,
  skill_needed TEXT NOT NULL,
  location TEXT NOT NULL,
  wage_offered TEXT NOT NULL,
  date_needed TEXT NOT NULL,
  status TEXT DEFAULT 'open',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Job Interests Table
CREATE TABLE IF NOT EXISTS job_interests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  worker_id BIGINT NOT NULL REFERENCES workers(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'interested',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_job_worker UNIQUE (job_id, worker_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_workers_skill_loc ON workers (skill_type, location, available);
CREATE INDEX IF NOT EXISTS idx_workers_phone ON workers (phone_number);
CREATE INDEX IF NOT EXISTS idx_jobs_skill_loc ON jobs (skill_needed, location, status);
CREATE INDEX IF NOT EXISTS idx_jobs_employer_phone ON jobs (employer_phone);
CREATE INDEX IF NOT EXISTS idx_job_interests_job ON job_interests (job_id);
CREATE INDEX IF NOT EXISTS idx_job_interests_worker ON job_interests (worker_id);

-- Enable Row Level Security (RLS)
ALTER TABLE workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_interests ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if re-running
DROP POLICY IF EXISTS "Allow all for workers" ON workers;
DROP POLICY IF EXISTS "Allow all for jobs" ON jobs;
DROP POLICY IF EXISTS "Allow all for job_interests" ON job_interests;

-- Policies allowing full access using public anon key (for backend API & direct client)
CREATE POLICY "Allow all for workers" ON workers
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow all for jobs" ON jobs
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow all for job_interests" ON job_interests
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);
