-- ==============================================================================
-- LabourLink Complete Database Schema & Migration for Supabase (PostgreSQL)
-- Project: https://rvjpikckmvossbvobzsx.supabase.co
-- ==============================================================================
-- Instructions:
-- 1. Open your Supabase Dashboard: https://supabase.com/dashboard/project/rvjpikckmvossbvobzsx/sql
-- 2. Click "New Query" (or paste into your SQL Editor).
-- 3. Paste this entire script into the query editor and click "Run" (Ctrl+Enter / Cmd+Enter).
-- ==============================================================================

-- Ensure schema permissions
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- 1. Workers Table
CREATE TABLE IF NOT EXISTS public.workers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone_number TEXT UNIQUE NOT NULL,
  skill_type TEXT NOT NULL,
  location TEXT NOT NULL,
  available BOOLEAN DEFAULT TRUE,
  status TEXT DEFAULT 'AVAILABLE',
  current_active_job_id BIGINT DEFAULT NULL,
  current_location_zone TEXT DEFAULT NULL,
  registered_at TIMESTAMPTZ DEFAULT NOW()
);

-- Safe column migrations for existing workers table
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'AVAILABLE';
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS current_active_job_id BIGINT DEFAULT NULL;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS current_location_zone TEXT DEFAULT NULL;

-- 2. Jobs Table
CREATE TABLE IF NOT EXISTS public.jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_name TEXT NOT NULL,
  employer_phone TEXT NOT NULL,
  skill_needed TEXT NOT NULL,
  location TEXT NOT NULL,
  wage_offered TEXT NOT NULL,
  date_needed TEXT NOT NULL,
  status TEXT DEFAULT 'open',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Job Interests Table
CREATE TABLE IF NOT EXISTS public.job_interests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  worker_id BIGINT NOT NULL REFERENCES public.workers(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'interested',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_job_worker UNIQUE (job_id, worker_id)
);

-- 4. Worker CV Table (Structured Form Data)
CREATE TABLE IF NOT EXISTS public.worker_cv (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT UNIQUE NOT NULL REFERENCES public.workers(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  dob_or_age TEXT,
  phone_number TEXT,
  skills TEXT,
  years_of_experience INTEGER DEFAULT 0,
  previous_work TEXT,
  work_location TEXT,
  daily_wage_expectation TEXT,
  availability_type TEXT DEFAULT 'Full-time',
  languages TEXT,
  about_me TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Worker Ratings Table (1-5 stars with comments, prevent duplicate per job)
CREATE TABLE IF NOT EXISTS public.worker_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT NOT NULL REFERENCES public.workers(id) ON DELETE CASCADE,
  employer_phone TEXT,
  job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  rating REAL NOT NULL CHECK (rating >= 1.0 AND rating <= 5.0),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_job_worker_rating UNIQUE (job_id, worker_id)
);

-- 6. JOB REJECTIONS (Job-scoped Rejection Tracking)
CREATE TABLE IF NOT EXISTS public.job_rejections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hirer_phone TEXT,
  job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE NOT NULL,
  worker_id BIGINT REFERENCES public.workers(id) ON DELETE CASCADE NOT NULL,
  reason TEXT,
  rejected_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_job_worker_rejection UNIQUE (job_id, worker_id)
);

-- Indexes for optimal query performance
CREATE INDEX IF NOT EXISTS idx_workers_skill_loc ON public.workers (skill_type, location, available);
CREATE INDEX IF NOT EXISTS idx_workers_phone ON public.workers (phone_number);
CREATE INDEX IF NOT EXISTS idx_jobs_skill_loc ON public.jobs (skill_needed, location, status);
CREATE INDEX IF NOT EXISTS idx_jobs_employer_phone ON public.jobs (employer_phone);
CREATE INDEX IF NOT EXISTS idx_job_interests_job ON public.job_interests (job_id);
CREATE INDEX IF NOT EXISTS idx_job_interests_worker ON public.job_interests (worker_id);
CREATE INDEX IF NOT EXISTS idx_job_rejections_job_worker ON public.job_rejections (job_id, worker_id);
CREATE INDEX IF NOT EXISTS idx_job_rejections_hirer_job ON public.job_rejections (hirer_phone, job_id);
CREATE INDEX IF NOT EXISTS idx_worker_cv_worker ON public.worker_cv (worker_id);
CREATE INDEX IF NOT EXISTS idx_worker_ratings_worker ON public.worker_ratings (worker_id);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_rejections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.worker_cv ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.worker_ratings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if re-running
DROP POLICY IF EXISTS "Allow all for workers" ON public.workers;
DROP POLICY IF EXISTS "Allow all for jobs" ON public.jobs;
DROP POLICY IF EXISTS "Allow all for job_interests" ON public.job_interests;
DROP POLICY IF EXISTS "Allow all for job_rejections" ON public.job_rejections;
DROP POLICY IF EXISTS "Allow all for worker_cv" ON public.worker_cv;
DROP POLICY IF EXISTS "Allow all for worker_ratings" ON public.worker_ratings;

-- Policies allowing full CRUD access via anon and authenticated roles
CREATE POLICY "Allow all for workers" ON public.workers
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for jobs" ON public.jobs
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for job_interests" ON public.job_interests
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for job_rejections" ON public.job_rejections
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for worker_cv" ON public.worker_cv
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for worker_ratings" ON public.worker_ratings
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Explicit table and sequence permissions for API clients
GRANT ALL ON TABLE public.workers TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.jobs TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.job_interests TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.job_rejections TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.worker_cv TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.worker_ratings TO anon, authenticated, service_role;

GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

-- Reload Supabase PostgREST schema cache immediately
NOTIFY pgrst, 'reload schema';
