-- ==============================================================================
-- LabourLink Database Migration: Enforce Unique Registrations
-- Prevents duplicate Worker and Hirer accounts by phone number and role
-- ==============================================================================

-- 1. Ensure UNIQUE constraint on workers table for phone_number
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'workers_phone_number_key'
  ) THEN
    ALTER TABLE workers ADD CONSTRAINT workers_phone_number_key UNIQUE (phone_number);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_workers_phone_unique ON workers (phone_number);

-- 2. Create Employers / Hirers Table with UNIQUE phone_number
CREATE TABLE IF NOT EXISTS employers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  company_name TEXT,
  location TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT employers_phone_number_key UNIQUE (phone_number)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_employers_phone_unique ON employers (phone_number);

-- Enable RLS for employers
ALTER TABLE employers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for employers" ON employers;
CREATE POLICY "Allow all for employers" ON employers
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- 3. Optional Unified Users Table with Composite UNIQUE constraint (phone_number, role)
-- Allows Option B (Role-Based Uniqueness: a user can be both a Worker and a Hirer,
-- but cannot register twice with the same phone for the same role).
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  email TEXT,
  role TEXT NOT NULL CHECK (role IN ('worker', 'hirer', 'employer')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_phone_role UNIQUE (phone_number, role)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone_role ON users (phone_number, role);

-- Enable RLS for users table
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for users" ON users;
CREATE POLICY "Allow all for users" ON users
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);
