-- IVR tables for PostgreSQL / Supabase
CREATE TABLE IF NOT EXISTS public.job_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  digit TEXT UNIQUE NOT NULL,
  category_name TEXT NOT NULL,
  hiring_agency_name TEXT NOT NULL,
  hiring_agency_phone TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.call_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_sid TEXT,
  caller_number TEXT,
  called_number TEXT,
  digit_selected TEXT,
  category_name TEXT,
  agency_name TEXT,
  agency_phone TEXT,
  routed BOOLEAN DEFAULT FALSE,
  outcome TEXT,
  connect_mode TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_job_categories_digit ON public.job_categories (digit, active);
CREATE INDEX IF NOT EXISTS idx_call_logs_sid ON public.call_logs (call_sid);
